[package]
name = "raytracer-in-one-week"
version = "0.1.0"
authors = ["Matthias Schorsch <matthias.schorsch@gmx.de>"]
edition = "2018"

[dependencies]
rand = "0.7.0"
vek = "0.9.8"

[profile.release]
lto = true