[package]
name = "raytracer-in-one-week"
version = "0.1.0"
authors = ["Matthias Schorsch <matthias.schorsch@gmx.de>"]
edition = "2018"

[dependencies]
rand = "0.7.0"
# minifb = "0.11.2"
# vek = "0.9.7"
